spring:
  application:
    name: eureka-server
server:
  port: 1000
eureka:
  server:
    enable-self-preservation: false #关闭保护功能
  instance:
    hostname: discovery
  client:
    register-with-eureka: false #此client不注册到Eureka Server
    fetch-registry: false #此client不从Eureka Server获取实例
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/