spring:
  application:
    name: api-gateway
###### zipkin配置 ####
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 2222
eureka:
  client:
    service-url:
      defaultZone: http://discovery:1000/eureka/
      
