spring:
  application:
    name: eureka-server
server:
  port: 1000
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: discovery
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/